name: Sync to Gitee

on:
  push:
    branches:
      - main  # 只在 main 分支被推送时触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitee
        uses: wei/git-sync@v3
        with:
          # 源仓库，这里是你的 GitHub 仓库地址
          source_repo: 'https://github.com/yinwm/persona-summoner-hub.git'
          source_branch: 'main'
          
          # 目标仓库，这里是你的 Gitee 仓库地址
          # 注意：需要把下面的 yinwm 替换为你的 Gitee 用户名
          destination_repo: 'https://yinwm:${{ secrets.GITEE_TOKEN }}@gitee.com/yinwm/persona-summoner-hub.git'
          destination_branch: 'main'
